import { TextStyle } from "react-native";

type IAppTextType = {
    boldHeading180: TextStyle,
    boldHeading260: TextStyle,
    boldHeading340: TextStyle,
    boldHeading430: TextStyle,
    boldHeading524: TextStyle,
    boldHeading620: TextStyle,
    boldBody16: TextStyle,
    boldCaption14: TextStyle,
    boldSmall12: TextStyle,
    boldTiny10: TextStyle,

    mediumHeading180: TextStyle,
    mediumHeading260: TextStyle,
    mediumHeading340: TextStyle,
    mediumHeading430: TextStyle,
    mediumHeading524: TextStyle,
    mediumHeading620: TextStyle,
    mediumBody16: TextStyle,
    mediumCaption14: TextStyle,
    mediumSmall12: TextStyle,
    mediumTiny10: TextStyle,

    regularHeading180: TextStyle,
    regularHeading260: TextStyle,
    regularHeading340: TextStyle,
    regularHeading430: TextStyle,
    regularHeading524: TextStyle,
    regularHeading620: TextStyle,
    regularBody16: TextStyle,
    regularCaption14: TextStyle,
    regularSmall12: TextStyle,
    regularTiny10: TextStyle,

    thinHeading180: TextStyle,
    thinHeading260: TextStyle,
    thinHeading340: TextStyle,
    thinHeading430: TextStyle,
    thinHeading524: TextStyle,
    thinHeading620: TextStyle,
    thinBody16: TextStyle,
    thinCaption14: TextStyle,
    thinSmall12: TextStyle,
    thinTiny10: TextStyle,
}

export const AppTextType: IAppTextType = {
    boldHeading180: {
        fontSize: 80,
        fontWeight: '900',
        lineHeight: 80,
        fontFamily: 'Ubuntu',
    },
    boldHeading260: {
        fontSize: 60,
        fontWeight: '900',
        lineHeight: 60,
        fontFamily: 'Ubuntu',
    },
    boldHeading340: {
        fontSize: 40,
        fontWeight: '900',
        lineHeight: 40,
        fontFamily: 'Ubuntu',
    },
    boldHeading430: {
        fontSize: 30,
        fontWeight: '900',
        lineHeight: 30,
        fontFamily: 'Ubuntu',
    },
    boldHeading524: {
        fontSize: 24,
        fontWeight: '900',
        lineHeight: 24,
        fontFamily: 'Ubuntu',
    },
    boldHeading620: {
        fontSize: 20,
        fontWeight: '900',
        lineHeight: 24,
        fontFamily: 'Ubuntu',
    },
    boldBody16: {
        fontSize: 16,
        fontWeight: '900',
        lineHeight: 20,
        fontFamily: 'Ubuntu',
    },
    boldCaption14: {
        fontSize: 14,
        fontWeight: '900',
        lineHeight: 22,
        fontFamily: 'Ubuntu',
    },
    boldSmall12: {
        fontSize: 12,
        fontWeight: '900',
        lineHeight: 18,
        fontFamily: 'Ubuntu',
    },
    boldTiny10: {
        fontSize: 10,
        fontWeight: '900',
        lineHeight: 16,
        fontFamily: 'Ubuntu',
    },
    mediumHeading180: {
        fontSize: 80,
        fontWeight: '600',
        lineHeight: 80,
        fontFamily: 'Ubuntu',
    },
    mediumHeading260: {
        fontSize: 60,
        fontWeight: '600',
        lineHeight: 60,
        fontFamily: 'Ubuntu',
    },
    mediumHeading340: {
        fontSize: 40,
        fontWeight: '600',
        lineHeight: 40,
        fontFamily: 'Ubuntu',
    },
    mediumHeading430: {
        fontSize: 30,
        fontWeight: '600',
        lineHeight: 30,
        fontFamily: 'Ubuntu',
    },
    mediumHeading524: {
        fontSize: 24,
        fontWeight: '600',
        lineHeight: 24,
        fontFamily: 'Ubuntu',
    },
    mediumHeading620: {
        fontSize: 20,
        fontWeight: '600',
        lineHeight: 24,
        fontFamily: 'Ubuntu',
    },
    mediumBody16: {
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 20,
        fontFamily: 'Ubuntu',
    },
    mediumCaption14: {
        fontSize: 14,
        fontWeight: '600',
        lineHeight: 22,
        fontFamily: 'Ubuntu',
    },
    mediumSmall12: {
        fontSize: 12,
        fontWeight: '600',
        lineHeight: 18,
        fontFamily: 'Ubuntu',
    },
    mediumTiny10: {
        fontSize: 10,
        fontWeight: '600',
        lineHeight: 16,
        fontFamily: 'Ubuntu',
    },
    regularHeading180: {
        fontSize: 80,
        fontWeight: '400',
        lineHeight: 80,
        fontFamily: 'Ubuntu',
    },
    regularHeading260: {
        fontSize: 60,
        fontWeight: '400',
        lineHeight: 60,
        fontFamily: 'Ubuntu',
    },
    regularHeading340: {
        fontSize: 40,
        fontWeight: '400',
        lineHeight: 40,
        fontFamily: 'Ubuntu',
    },
    regularHeading430: {
        fontSize: 30,
        fontWeight: '400',
        lineHeight: 30,
        fontFamily: 'Ubuntu',
    },
    regularHeading524: {
        fontSize: 24,
        fontWeight: '400',
        lineHeight: 24,
        fontFamily: 'Ubuntu',
    },
    regularHeading620: {
        fontSize: 20,
        fontWeight: '400',
        lineHeight: 24,
        fontFamily: 'Ubuntu',
    },
    regularBody16: {
        fontSize: 16,
        fontWeight: '400',
        lineHeight: 20,
        fontFamily: 'Ubuntu',
    },
    regularCaption14: {
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 22,
        fontFamily: 'Ubuntu',
    },
    regularSmall12: {
        fontSize: 12,
        fontWeight: '400',
        lineHeight: 18,
        fontFamily: 'Ubuntu',
    },
    regularTiny10: {
        fontSize: 10,
        fontWeight: '400',
        lineHeight: 16,
        fontFamily: 'Ubuntu',
    },
    thinHeading180: {
        fontSize: 80,
        fontWeight: '400',
        fontStyle: 'italic',
        lineHeight: 80,
        fontFamily: 'Ubuntu',
    },
    thinHeading260: {
        fontSize: 60,
        fontWeight: '400',
        fontStyle: 'italic',
        lineHeight: 60,
        fontFamily: 'Ubuntu',
    },
    thinHeading340: {
        fontSize: 40,
        fontWeight: '400',
        fontStyle: 'italic',
        lineHeight: 40,
        fontFamily: 'Ubuntu',
    },
    thinHeading430: {
        fontSize: 30,
        fontWeight: '400',
        fontStyle: 'italic',
        lineHeight: 30,
        fontFamily: 'Ubuntu',
    },
    thinHeading524: {
        fontSize: 24,
        fontWeight: '400',
        fontStyle: 'italic',
        lineHeight: 24,
        fontFamily: 'Ubuntu',
    },
    thinHeading620: {
        fontSize: 20,
        fontWeight: '400',
        fontStyle: 'italic',
        lineHeight: 24,
        fontFamily: 'Ubuntu',
    },
    thinBody16: {
        fontSize: 16,
        fontWeight: '400',
        fontStyle: 'italic',
        lineHeight: 20,
        fontFamily: 'Ubuntu',
    },
    thinCaption14: {
        fontSize: 14,
        fontWeight: '400',
        fontStyle: 'italic',
        lineHeight: 22,
        fontFamily: 'Ubuntu',
    },
    thinSmall12: {
        fontSize: 12,
        fontWeight: '400',
        fontStyle: 'italic',
        lineHeight: 18,
        fontFamily: 'Ubuntu',
    },
    thinTiny10: {
        fontSize: 10,
        fontStyle: 'italic',
        fontWeight: '400',
        lineHeight: 16,
        fontFamily: 'Ubuntu',
    },
}